# Generated by Django 4.1.6 on 2023-05-29 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='Male', max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 5, 29, 11, 54, 24, 468726))),
                ('stack', models.CharField(default='Flutter', max_length=50)),
                ('programing', models.TextField()),
                ('status', models.CharField(default='published', max_length=50)),
            ],
            options={
                'verbose_name': ('Customer',),
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
