# Generated by Django 4.1.6 on 2023-05-29 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': ('Portfolio',), 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 12, 8, 5, 253489)),
        ),
    ]
