# Generated by Django 4.1.6 on 2023-05-29 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 12, 10, 34, 729405)),
        ),
    ]
